### PR TITLE
Integrate Segment and add a few events to Segment

### PR DESCRIPTION
**Pull request by mmjee**
# Pull Request Template

Resolves or continues [AR-4043](https://team-1624093970686.atlassian.net/browse/AR-4033).

Mixpanel: https://eu.mixpanel.com/project/2783221/view/3318109/app/dashboards .

## Blocking dependencies

None

## Changes

Added the Segment analytics SDK, implemented upload and download tracking.

## Checklist

- [x] The branch name follows the format: `developer/AR-XXX-issue-name`.
- [x] The changes have been tested locally.

### CODE REVIEW

**Comment by mmjee** [comment]
Once again, the lint errors are not related to this PR. No new errors have been introduced.

**Comment by mmjee** [comment]
Once again, the lint errors are not related to this PR. No new errors have been introduced.
Passive voice

The text seems to be passive voice. To make the text clearer and easier to read, you can often use the active voice.

Turn off rule everywhere

Ignore in this text

Turn off picky mode in this text

LanguageTool

basic

**Comment by shaloo** [comment]
> Once again, the lint errors are not related to this PR. No new errors have been introduced. Passive voice The text seems to be passive voice. To make the text clearer and easier to read, you can often use the active voice. Turn off rule everywhere Ignore in this text Turn off picky mode in this text LanguageTool basic

@mmjee what was this feedback for? Code or docs elsewhere? just curious.

**Comment by mmjee** [comment]
On 11/10/22 21:03, shalz wrote:
>> Once again, the lint errors are not related to this PR. No new errors have been introduced. Passive voice The text seems to be passive voice. To make the text clearer and easier to read, you can often use the active voice. Turn off rule everywhere Ignore in this text Turn off picky mode in this text LanguageTool basic
> 
> @mmjee what was this feedback for? Code or docs elsewhere? just curious.
> 
Probably just the email, I didn't even notice the warnings were somehow copy-pasted into the email.
-- 
Regards,

**Pull request closed without merging**
