### PR TITLE
Fix the typings for anonymous arrow functions and handle exported internal types

### PR DESCRIPTION
**Pull request by mmjee**
References:
1. https://team-1624093970686.atlassian.net/browse/AR-3323

### CODE REVIEW

**Comment by shaloo** [comment]
@mmjee I just checked out this branch and built htmldocs.  I still see _login showing up.  🤔
Screen Shot 2022-07-06 at 2 46 17 PM

**Comment by shaloo** [comment]
If you compare the generated storage SDK ref guide using this branch and the one deployed here from dev branch - there is no visible difference. What did i miss? https://storagesdk-ref-guide.netlify.app/classes/storageprovider

**Comment by mmjee** [comment]
If you check out the Netlify deployment, you'll see that _login has disappeared, and I can see the previously hidden types. I don't know how it doesn't show up locally on your side, but it works fine on mine.

See: https://deploy-preview-78--storagesdk-ref-guide.netlify.app/classes/storageprovider#login

**Comment by shaloo** [comment]
LGTM

**Review by SauravKanchan — APPROVED** [review]

**Pull request merged**
